openapi: 3.0.0
info:
  title: Blog App
  description: API for creating, retrieving, updating, and deleting blogs.
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local Server
paths:
  /auth/signup:
    post:
      summary: User Sign-Up
      description: Create a new user account.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignUpInput'
      responses:
        '201':
          description: User created successfully.
        '400':
          description: Invalid input data.
  /auth/signin:
    post:
      summary: User Sign-In
      description: Authenticate a user and return a token.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignInInput'
      responses:
        '200':
          description: Authentication successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '401':
          description: Authentication failed.
  /blogs:
    get:
      summary: Get all blogs
      description: Retrieve a list of all blogs.
      responses:
        '200':
          description: A list of blogs.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Blog'
    post:
      summary: Create a new blog
      description: Add a new blog to the system.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BlogInput'
      responses:
        '201':
          description: Blog created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Blog'
  /blogs/{id}:
    get:
      summary: Get a blog by ID
      description: Retrieve a blog by its unique identifier.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The ID of the blog.
      responses:
        '200':
          description: The blog details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Blog'
        '404':
          description: Blog not found.
    put:
      summary: Update a blog
      description: Update an existing blog by its unique identifier.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The ID of the blog to update.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BlogInput'
      responses:
        '200':
          description: Blog updated successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Blog'
        '404':
          description: Blog not found.
    delete:
      summary: Delete a blog
      description: Delete an existing blog by its unique identifier.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The ID of the blog to delete.
      responses:
        '204':
          description: Blog deleted successfully.
        '404':
          description: Blog not found.
components:
  schemas:
    SignUpInput:
      type: object
      properties:
        Email:
          type: string
          description: User's email address.
        Password:
          type: string
          description: User's password.
    SignInInput:
      type: object
      properties:
        Email:
          type: string
          format: email
        Password:
          type: string
          description: User's password.
    AuthResponse:
      type: object
      properties:
        Token:
          type: string
          description: JWT token for authenticated requests.
    Blog:
      type: object
      properties:
        ID:
          type: string
          description: Unique identifier of the blog.
        Title:
          type: string
          description: Title of the blog.
        Content:
          type: string
          description: Main content of the blog.
        Author:
          type: string
          description: Name of the blog's author.
        CreatedAt:
          type: string
          description: Timestamp when the blog was created.
        UpdatedAt:
          type: string
          description: Timestamp when the blog was last updated.
    BlogInput:
      type: object
      properties:
        Title:
          type: string
          description: Title of the blog.
        Content:
          type: string
          description: Main content of the blog.
        Author:
          type: string
          description: Name of the blog's author.


